const Questions = [
  {
    prompt: " Who are the founders of Google?",
    optionA: "Larry Page and Sergey Brin",
    optionB: "Ronaldo",
    optionC: "Kalam",
    optionD: "Larry Page",
    answer: "A",
  },
  {
    prompt: " Which is the largest continent?",
    optionA: "Iran",
    optionB: "Asia",
    optionC: "America",
    optionD: "Europ",
    answer: "B",
  },
  {
    prompt: "Who founded Facebook?",
    optionA: "Elon Musk",
    optionB: "Jawed Karim",
    optionC: "Mark Zuckerberg",
    optionD: "Galileo Galilei",
    answer: "C",
  },
  {
    prompt: "Which is the longest river on Earth?",
    optionA: "Elon Musk",
    optionB: "Einsteins",
    optionC: "Jawed Karim",
    optionD: "Nile river in Egypt",
    answer: "D",
  },
  {
    prompt: "Who invented the Light Bulb?",
    optionA: "Thomas Alva Edison",
    optionB: "Einsteins",
    optionC: "Kalam",
    optionD: "Galileo Galilei",
    answer: "A",
  },
  {
    prompt: "Who invented the Computer?",
    optionA: "Thomas Alva Edison",
    optionB: "Einsteins",
    optionC: "Charles Babbage ",
    optionD: "Galileo Galilei",
    answer: "C",
  },
  {
    prompt: "Which planet in our solar system is known as the Red Planet?",
    optionA: "Mars",
    optionB: "Earth",
    optionC: "Venus",
    optionD: "Mercury",
    answer: "A",
  },
  {
    prompt: "What is the name of the biggest planet in our solar system?",
    optionA: "Venus",
    optionB: "Mercury",
    optionC: "Jupiter",
    optionD: "Neptune",
    answer: "C",
  },
  {
    prompt: "Who invented the Telephone?",
    optionA: "Robert Boyle",
    optionB: "Louis Pasteur",
    optionC: "Galileo Galilei",
    optionD: "Alexander Graham Bell",
    answer: "D",
  },
  {
    prompt: "Who discovered Penicillin?",
    optionA: "Alber",
    optionB: "Kalam",
    optionC: "Alexander Fleming",
    optionD: "John Dalton",
    answer: "C",
  },
  {
    prompt: " 1 L is equal to how many grams?",
    optionA: "1000 ml",
    optionB: "100L",
    optionC: "200ml",
    optionD: "5000ml",
    answer: "A",
  },
  {
    prompt:
      " When a number is multiplied by zero, the answer you get is always ____?",
    optionA: "Zero",
    optionB: "1",
    optionC: "001",
    optionD: "-1",
    answer: "A",
  },
  {
    prompt: "The largest 4 digit number is?",
    optionA: "4444",
    optionB: "1",
    optionC: "9999",
    optionD: "5001",
    answer: "C",
  },
  {
    prompt: "What is the National Song of India?",
    optionA: "Sare Jahan Se Achha Hindustan Hamara",
    optionB: "hindi song",
    optionC: "Ham Jiyenge Aur Marenge,Dil Diya Hai Jaan Bhi ...",
    optionD: "Vande Mataram",
    answer: "D",
  },
  {
    prompt: "Who is known as the Father of the Indian Constitution?",
    optionA: "Dr B. R. Ambedkar",
    optionB: "Jawaharlal Nehru",
    optionC: "Ali Jinna",
    optionD: "Dr Rajendra Prasad",
    answer: "A",
  },
];
export default Questions;
