const Menu = [
  {
    id: 1,
    image: "./image/maggi.jpg",
    name: "maggi",
    price: "12 $",
    category: "breakfast",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 2,
    image: "./image/corn.jpg",
    name: "Corn",
    price: "12 $",
    category: "evening",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 3,
    image: "./image/egg.jpg",
    name: "morning",
    price: "12 $",
    category: "breakfast",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 4,
    image: "./image/mattar.jpg",
    name: "Mattar",
    price: "12 $",
    category: "breakfast",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 5,
    image: "./image/Patato.jpg",
    name: "Patato",
    price: "12 $",
    category: "evening",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 6,
    image: "./image/egg.jpg",
    name: "Egg",
    price: "12 $",
    category: "morning",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 7,
    image: "./image/egg.jpg",
    name: "Egg",
    price: "12 $",
    category: "dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 8,
    image: "./image/corn.jpg",
    name: "Egg",
    price: "12 $",
    category: "evening",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 9,
    image: "./image/egg.jpg",
    name: "Egg",
    price: "12 $",
    category: "morning",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 10,
    image: "./image/corn.jpg",
    name: "Egg",
    price: "12 $",
    category: "breakfast",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 11,
    image: "./image/egg.jpg",
    name: "Egg",
    price: "12 $",
    category: "evening",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 12,
    image:"./image/corn.jpg",
    name: "Egg",
    price: "12 $",
    category: "dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 13,
    image: "./image/egg.jpg",
    name: "Egg",
    price: "12 $",
    category: "morning",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 14,
    image: "./image/corn.jpg",
    name: "Egg",
    price: "12 $",
    category: "dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 15,
    image: "./image/egg.jpg",
    name: "Egg",
    price: "12 $",
    category: "evening",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 15,
    image:"./image/Patato.jpg",
    name: "All",
    price: "12 $",
    category: "dinner",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
];
export default Menu;
